config/routes.rb
ProiectConf::Application.routes.draw do

  devise_for :users

  resources :pacients, :has_many => :diabets
  resources :pacients, :has_many => :protocols #, :member => { :last_protocol => :get }
  resources :pacients, :has_many => :capds
  resources :pacients, :hay_many => :hemo_lunars
  resources :pacients, :hay_many => :bcrs

  resources :pacients do 
    resources :capds
    resources :bcrs 
    resources :protocols 
    resources :diabets
    resources :hemo_lunars
    resources :hemo_semestrials
  end
  resources :diabets
  resources :hemo_lunars
  resources :bcrs
  resources :capds

  resources :protocols do 
    resources :centrus
  end

  resources :centrus 
  root :to => "pacients#index"

end

app/models/hemo_semestrial.rb
class HemoSemestrial < ActiveRecord::Base
  belongs_to :pacient
end

app/controllers/hemo_semestrials_controller.rb
class HemoSemestrialsController < ApplicationController
  # GET /hemo_semestrials
  # GET /hemo_semestrials.xml
  before_filter :find_pacient, :except => [:show]
  def index
    @hemo_semestrials = HemoSemestrial.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @hemo_semestrials }
    end
  end

  # GET /hemo_semestrials/1
  # GET /hemo_semestrials/1.xml
  def show
    @hemo_semestrial = HemoSemestrial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @hemo_semestrial }
    end
  end

  # GET /hemo_semestrials/new
  # GET /hemo_semestrials/new.xml
  def new
    @hemo_semestrial = HemoSemestrial.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @hemo_semestrial }
    end
  end

  # GET /hemo_semestrials/1/edit
  def edit
    @hemo_semestrial = HemoSemestrial.find(params[:id])
  end

  # POST /hemo_semestrials
  # POST /hemo_semestrials.xml
  def create
    @hemo_semestrial = HemoSemestrial.new(params[:hemo_semestrial])

    respond_to do |format|
      if @hemo_semestrial.save
        format.html { redirect_to(@hemo_semestrial, :notice => 'Hemo semestrial was successfully created.') }
        format.xml  { render :xml => @hemo_semestrial, :status => :created, :location => @hemo_semestrial }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @hemo_semestrial.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /hemo_semestrials/1
  # PUT /hemo_semestrials/1.xml
  def update
    @hemo_semestrial = HemoSemestrial.find(params[:id])

    respond_to do |format|
      if @hemo_semestrial.update_attributes(params[:hemo_semestrial])
        format.html { redirect_to(@hemo_semestrial, :notice => 'Hemo semestrial was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @hemo_semestrial.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /hemo_semestrials/1
  # DELETE /hemo_semestrials/1.xml
  def destroy
    @hemo_semestrial = HemoSemestrial.find(params[:id])
    @hemo_semestrial.destroy

    respond_to do |format|
      format.html { redirect_to(hemo_semestrials_url) }
      format.xml  { head :ok }
    end
  end
  private
  def find_pacient
    @pacient = params[:pacient_id] ? Pacient.find(params[:pacient_id]) : Pacient.find(params[:id])
  end
end

app/helpers/hemo_semestrials_helper.rb
module HemoSemestrialsHelper
end

app/views/hemo_semestrials/_form.html.erb
<%= form_for([@pacient, @pacient.hemo_semestrials.build]) do |f| %>
  <% if @hemo_semestrial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hemo_semestrial.errors.count, "error") %> prohibited this hemo_semestrial from being saved:</h2>

      <ul>
      <% @hemo_semestrial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :aghbs %><br />
    <%= f.text_field :aghbs %>
  </div>
  <div class="field">
    <%= f.label :achbs %><br />
    <%= f.text_field :achbs %>
  </div>
  <div class="field">
    <%= f.label :achcv %><br />
    <%= f.text_field :achcv %>
  </div>
  <div class="field">
    <%= f.label :achiv %><br />
    <%= f.text_field :achiv %>
  </div>
  <div class="field">
    <%= f.label :pth %><br />
    <%= f.text_field :pth %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hemo_semestrials/edit.html.erb
<h1>Editing hemo_semestrial</h1>

<%= render 'form' %>

<%= link_to 'Show', @hemo_semestrial %> |
<%= link_to 'Back', hemo_semestrials_path %>

app/views/hemo_semestrials/index.html.erb
<h1>Listing hemo_semestrials</h1>

<table>
  <tr>
    <th>Data</th>
    <th>Aghbs</th>
    <th>Achbs</th>
    <th>Achcv</th>
    <th>Achiv</th>
    <th>Pth</th>
    <th>Pacient</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hemo_semestrials.each do |hemo_semestrial| %>
  <tr>
    <td><%= hemo_semestrial.data %></td>
    <td><%= hemo_semestrial.aghbs %></td>
    <td><%= hemo_semestrial.achbs %></td>
    <td><%= hemo_semestrial.achcv %></td>
    <td><%= hemo_semestrial.achiv %></td>
    <td><%= hemo_semestrial.pth %></td>
    <td><%= hemo_semestrial.pacient %></td>
    <td><%= link_to 'Show', pacient_hemo_semestrials_path %></td>
    <td><%= link_to 'Edit', edit_pacient_hemo_semestrial_path(hemo_semestrial) %></td><!-- asta nu merge -->
    <td><%= link_to 'Destroy', hemo_semestrial, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hemo semestrial', new_pacient_hemo_semestrials_path %>

app/views/hemo_semestrials/new.html.erb
<h1>New hemo_semestrial</h1>

<%= render 'form' %>

<%= link_to 'Back', pacient_hemo_semestrials_path %>

app/views/hemo_semestrials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Data:</b>
  <%= @hemo_semestrial.data %>
</p>

<p>
  <b>Aghbs:</b>
  <%= @hemo_semestrial.aghbs %>
</p>

<p>
  <b>Achbs:</b>
  <%= @hemo_semestrial.achbs %>
</p>

<p>
  <b>Achcv:</b>
  <%= @hemo_semestrial.achcv %>
</p>

<p>
  <b>Achiv:</b>
  <%= @hemo_semestrial.achiv %>
</p>

<p>
  <b>Pth:</b>
  <%= @hemo_semestrial.pth %>
</p>

<p>
  <b>Pacient:</b>
  <%= @hemo_semestrial.pacient %>
</p>


<%= link_to 'Edit', edit_hemo_semestrial_path(@hemo_semestrial) %> |
<%= link_to 'Back', hemo_semestrials_path %>