config/routes.rb
ProiectConf::Application.routes.draw do

  devise_for :users

  resources :pacients, :has_many => :diabets
  resources :pacients, :has_many => :protocols #, :member => { :last_protocol => :get }
  resources :pacients, :has_many => :capds
  resources :pacients, :hay_many => :hemo_lunars
  resources :pacients, :hay_many => :bcrs

  resources :pacients do 
    resources :capds
    resources :bcrs 
    resources :protocols 
    resources :diabets
    resources :hemo_lunars
    resources :hemo_semestrials
  end
  resources :diabets
  resources :hemo_lunars
  resources :bcrs
  resources :capds

  resources :protocols do 
    resources :centrus
  end

  resources :centrus 
  root :to => "pacients#index"

end

app/models/diabet.rb
class Diabet < ActiveRecord::Base
  belongs_to :pacient
end

app/controllers/diabets_controller.rb
class DiabetsController < ApplicationController
  before_filter :find_pacient
  # GET /diabets
  # GET /diabets.xml
  def index
    @diabets = @pacient.diabets.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @diabets }
    end
  end

  # GET /diabets/1
  # GET /diabets/1.xml
  def show
    @diabet = @pacient.diabets.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @diabet }
    end
  end

  # GET /diabets/new
  # GET /diabets/new.xml
  def new
    @diabet = @pacient.diabets.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @diabet }
    end
  end

  # GET /diabets/1/edit
  def edit
    @diabet = @pacient.diabets.find(params[:id])
  end

  # POST /diabets
  # POST /diabets.xml
  def create
    @diabet = @pacient.diabets.new

    respond_to do |format|
      if @diabet.save
        format.html { redirect_to(@diabet, :notice => 'Diabet was successfully created.') }
        format.xml  { render :xml => @diabet, :status => :created, :location => @diabet }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @diabet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /diabets/1
  # PUT /diabets/1.xml
  def update
    @diabet = @pacient.diabets.find(params[:id])

    respond_to do |format|
      if @diabet.update_attributes(params[:diabet])
        format.html { redirect_to(@diabet, :notice => 'Diabet was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @diabet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /diabets/1
  # DELETE /diabets/1.xml
  def destroy
    @diabet = @pacient.diabets.find(params[:id])
    @diabet.destroy

    respond_to do |format|
      format.html { redirect_to(diabets_url) }
      format.xml  { head :ok }
    end
  end

  def find_pacient
    @pacient = Pacient.find(params[:pacient_id])
  end

end

app/helpers/diabets_helper.rb
module DiabetsHelper
end

app/views/diabets/_form.html.erb
<%= form_for([@pacient, @diabet]) do |f| %>
  <% if @diabet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diabet.errors.count, "error") %> prohibited this diabet from being saved:</h2>

      <ul>
      <% @diabet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diabets/edit.html.erb
<h1>Editing diabet</h1>

<%= render 'form' %>

<%= link_to 'Show', @diabet %> |
<%= link_to 'Back', diabets_path %>

app/views/diabets/index.html.erb
<h1>Listing diabets</h1>

<table>
  <tr>
    <th>Data</th>
    <th>Pacient</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @diabets.each do |diabet| %>
  <tr>
    <td><%= diabet.data %></td>
    <td><%= diabet.pacient %></td>
    <td><%= link_to 'Show', diabet %></td>
    <td><%= link_to 'Edit', edit_diabet_path(diabet) %></td>
    <td><%= link_to 'Destroy', diabet, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Diabet', new_diabet_path %>

app/views/diabets/new.html.erb
<h1>New diabet</h1>

<%= render 'form' %>

<%= link_to 'Back', diabets_path %>

app/views/diabets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Data:</b>
  <%= @diabet.data %>
</p>

<p>
  <b>Pacient:</b>
  <%= @diabet.pacient %>
</p>


<%= link_to 'Edit', edit_diabet_path(@diabet) %> |
<%= link_to 'Back', diabets_path %>