config/routes.rb
ProiectConf::Application.routes.draw do

  devise_for :users

  resources :pacients, :has_many => :diabets
  resources :pacients, :has_many => :protocols #, :member => { :last_protocol => :get }
  resources :pacients, :has_many => :capds
  resources :pacients, :hay_many => :hemo_lunars
  resources :pacients, :hay_many => :bcrs

  resources :pacients do 
    resources :capds
    resources :bcrs 
    resources :protocols 
    resources :diabets
    resources :hemo_lunars
    resources :hemo_semestrials
  end
  resources :diabets
  resources :hemo_lunars
  resources :bcrs
  resources :capds

  resources :protocols do 
    resources :centrus
  end

  resources :centrus 
  root :to => "pacients#index"

end

app/models/hemo_lunar.rb
class HemoLunar < ActiveRecord::Base
  belongs_to :pacient
  def self.analize_list
    hemo_lunar=self.column_names
    hemo_lunar= hemo_lunar.drop(5)
    analize_semestrial = HemoSemestrial.column_names
    analize_semestrial= analize_semestrial.drop(2)
    analize_semestrial.pop(3)
    analize = {'Protocol Lunar'=> hemo_lunar, 'Protocol Semestrial' => analize_semestrial}
  end

end

app/controllers/hemo_lunars_controller.rb
class HemoLunarsController < ApplicationController

 before_filter :find_pacient, :except => [:show]
  # GET /hemo_lunars
  # GET /hemo_lunars.xml
  def index
    @hemo_lunars = @pacient.hemo_lunars.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.js #index.js.erb
      format.xml  { render :xml => @hemo_lunars }
    end
  end

  # GET /hemo_lunars/1
  # GET /hemo_lunars/1.xml
  def show
    @hemo_lunar = HemoLunar.find(params[:id])
  end

  # GET /hemo_lunars/new
  # GET /hemo_lunars/new.xml
  def new
    @hemo_lunar = @pacient.hemo_lunars.new
  end

  # GET /hemo_lunars/1/edit
  def edit
    @hemo_lunar = @pacient.hemo_lunars.find(params[:id])
  end

  # POST /hemo_lunars
  # POST /hemo_lunars.xml
  def create
    @hemo_lunar = @pacient.protocols.create(params[:id]) #inca nu merge
  end

  # PUT /hemo_lunars/1
  # PUT /hemo_lunars/1.xml
  def update
    @hemo_lunar = hemo_lunar.find(params[:id])

    respond_to do |format|
      if @hemo_lunar.update_attributes(params[:hemo_lunar])
        format.html { redirect_to(@hemo_lunar, :notice => 'hemo_lunar was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @hemo_lunar.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /hemo_lunars/1
  # DELETE /hemo_lunars/1.xml
  def destroy
    @hemo_lunar = @pacient.hemo_lunars.find(params[:id])
    @hemo_lunar.destroy

    respond_to do |format|
      format.html { redirect_to(pacient_hemo_lunars_url(@pacient)) }
      format.xml  { head :ok }
    end
  end
  private
  def find_pacient
    @pacient = params[:pacient_id] ? Pacient.find(params[:pacient_id]) : Pacient.find(params[:id])
  end
end

app/helpers/hemo_lunar_helper.rb
module HemoLunarHelper
end

app/views/hemo_lunars/_form.html.erb
    <h3> Protocol lunar </h3>
<%= simple_form_for @pacient do |d| %>
  <%= d.simple_fields_for :hemo_lunar do |f| %>
    <%= f.input :data, :as => :date %>
    <%= f.input :hemoglobina, :hint => 'mg/dL' %> 
    <%= f.input :hematocrit , :hint => '%'%>
    <%= f.input :hematii , :hint => 'mii/uL'%>
    <%= f.input :leucocite, :hint => 'mii/uL' %>
    <%= f.input :trombocite, :hint => 'mii/uL' %>
    <%= f.input :uree, :hint => 'mg/dL' %>
    <%= f.input :creatinina, :hint => 'mg/dL' %>
    <%= f.input :sodiu, :hint => 'mmol/L' %>
    <%= f.input :potasiu, :hint => 'mmol/L' %>
    <%= f.input :tgo, :hint => 'UI/L' %>
    <%= f.input :tgp, :hint => 'UI/L' %>
    <%= f.input :glicemie, :hint => 'mg/dL' %>
    <%= f.input :calciu, :hint => 'mg/dL' %>
    <%= f.input :fosfor, :hint => 'mg/dL' %>
  <% end %>
  <div class="actions">
    <%= d.submit  'salveaza si introdu semestrial', :name=> 'next_form' %>
    <%# d.submit @hemo_lunar.name_of_previous_step, :name => "previous_button" unless @hemo_lunar.first_step? %>
    <%= d.submit 'salveaza' , :name=> 'save_ahead', :confirm => 'vrei sa bagi doar formularele astea?' %>
  </div>
  <div>
    <%= link_to 'Semestrial', new_pacient_hemo_semestrial_path %>
  </div>
<% end %>

app/views/hemo_lunars/_index.html.erb
<!-- asta de ce nu e form? -->
<h4> daca nu are analize?</h4>
<table align="center">
  <tr>
    <th>Data</th>
    <th>Creatinina </th>
    <th> <%= select('nume', 'prenume', grouped_options_for_select(HemoLunar.analize_list),{:prompt => 'Selecteaza Analiza'}, 
                    :remote => true ) %>  </th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <h2> <%= @pacient.nume %></h2>
  <div id="analize_pacient">
<% for hemo_lunar in @pacient.hemo_lunars  %>
  <tr>
    <td><%= hemo_lunar.data %></td>
    <td align="center"><%= hemo_lunar.creatinina %></td>
    <td align="center"><%= hemo_lunar.hemoglobina %></td>
    <td><%= link_to 'Show', pacient_hemo_lunar_path(@pacient, hemo_lunar) %></td><!-- astea 3 nu sunt corecte -->
    <td><%= link_to 'Edit', edit_pacient_hemo_lunar_path(@pacient, hemo_lunar) %></td>
    <td><%= link_to 'Destroy', pacient_hemo_lunar_path(@pacient, hemo_lunar), 
      :confirm => 'Are you sure?', 
      :method => :delete %></td>
  </tr>
<% end %>
</div>
</table>

<br />

app/views/hemo_lunars/_index.js.erb
alert('ceva');

app/views/hemo_lunars/_lunar.html.erb
 <h3> Protocol lunar </h3>
   <div class="field">
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </div>
<div class="field">
    <%= f.label :hemoglobina %>
    <%= f.text_field :hemoglobina %>
  </div>
  <div class="field">
    <%= f.label :hematocrit %>
    <%= f.text_field :hematocrit %>
  </div>
 <div class="field">
    <%= f.label :hematii %>
    <%= f.text_field :hematii %>
  </div>
 <div class="field">
    <%= f.label :leucocite %>
    <%= f.text_field :leucocite %>
  </div>
 <div class="field">
    <%= f.label :trombocite %>
    <%= f.text_field :trombocite %>
  </div>
 <div class="field">
    <%= f.label :uree %>
    <%= f.text_field :uree %>
  </div>
 <div class="field">
    <%= f.label :creatinina %>
    <%= f.text_field :creatinina %>
  </div>
 <div class="field">
    <%= f.label :sodiu %>
    <%= f.text_field :sodiu %>
  </div>
 <div class="field">
    <%= f.label :potasiu %>
    <%= f.text_field :potasiu %>
  </div>
 <div class="field">
    <%= f.label :tgo %>
    <%= f.text_field :tgo %>
  </div>
 <div class="field">
    <%= f.label :tgp %>
    <%= f.text_field :tgp %>
  </div>
 <div class="field">
    <%= f.label :glicemie %>
    <%= f.text_field :glicemie %>
  </div>
 <div class="field">
    <%= f.label :calciu %>
    <%= f.text_field :calciu %>
  </div>
 <div class="field">
    <%= f.label :fosfor %>
    <%= f.text_field :fosfor %>
  </div>
  <div class="field">
    <%= f.label :greutate %>
    <%= f.text_field :greutate %>
  </div>
 <div class="field">
    <%= f.label :sga %>
    <%= f.text_field :sga %>
  </div>
 <div class="field">
    <%= f.label :tas %>
    <%= f.text_field :tas %>
  </div>
 <div class="field">
    <%= f.label :tad %>
    <%= f.text_field :tad %>
  </div>
 <div class="field">
    <%= f.label :indice_b_mortalitate %>
    <%= f.text_field :indice_b_mortalitate %>
  </div>
 <div class="field">
    <%= f.label :spitalizare %>
    <%= f.text_field :spitalizare %>
  </div>
 <div class="field">
    <%= f.label :vit_d %>
    <%= f.text_field :vit_d %>
  </div>
 <div class="field">
    <%= f.label :binder_fosfor %>
    <%= f.text_field :binder_fosfor %>
  </div>
 <div class="field">
    <%= f.label :epo_saptamana %>
    <%= f.text_field :epo_saptamana %>
  </div>
 <div class="field">
    <%= f.label :durata_hd %>
    <%= f.text_field :durata_hd %>
  </div>
  <div class="field">
    <%= f.label :heparina_dializa %>
    <%= f.text_field :heparina_dializa %>
  </div>

app/views/hemo_lunars/_semestrial.html.erb
  <h3> Analize hemo_lunar semestriale </h3>
 <div class="field">
    <%= f.label :aghbs %>
    <%= f.text_field :aghbs %>
  </div>
 <div class="field">
    <%= f.label :achbs %>
    <%= f.text_field :achbs %>
  </div>
 <div class="field">
    <%= f.label :achcv %>
    <%= f.text_field :achcv %>
  </div>
 <div class="field">
    <%= f.label :achiv %>
    <%= f.text_field :achiv %>
  </div>
 <div class="field">
    <%= f.label :pth %>
    <%= f.text_field :pth %>
  </div>

app/views/hemo_lunars/_trimestrial.html.erb
   <h3> Analize hemo_lunar trimestriale</h3>
 <div class="field">
    <%= f.label :fier_seric %>
    <%= f.text_field :fier_seric %>
  </div>
 <div class="field">
    <%= f.label :colesterol %>
    <%= f.text_field :colesterol %>
  </div>
 <div class="field">
    <%= f.label :lipide %>
    <%= f.text_field :lipide %>
  </div>
 <div class="field">
    <%= f.label :trigliceride %>
    <%= f.text_field :trigliceride %>
  </div>
 <div class="field">
    <%= f.label :ctlf %>
    <%= f.text_field :ctlf %>
  </div>
 <div class="field">
    <%= f.label :inr %>
    <%= f.text_field :inr %>
  </div>
 <div class="field">
    <%= f.label :aptt %>
    <%= f.text_field :aptt %>
  </div>
 <div class="field">
    <%= f.label :ap %>
    <%= f.text_field :ap %>
  </div>
 <div class="field">
    <%= f.label :fibrinogen %>
    <%= f.text_field :fibrinogen %>
  </div>
 <div class="field">
    <%= f.label :tquick %>
    <%= f.text_field :tquick %>
  </div>
 <div class="field">
    <%= f.label :proteine_serice %>
    <%= f.text_field :proteine_serice %>
  </div>
 <div class="field">
    <%= f.label :hemoglobina_glicozilata %>
    <%= f.text_field :hemoglobina_glicozilata %>
  </div>
 <div class="field">
    <%= f.label :saturarea_transferinei %>
    <%= f.text_field :saturarea_transferinei %>
  </div>
 <div class="field">
    <%= f.label :pcr %>
    <%= f.text_field :pcr %>
  </div>
 <div class="field">
    <%= f.label :urr %>
    <%= f.text_field :urr %>
  </div>
 <div class="field">
    <%= f.label :ektv %>
    <%= f.text_field :ektv %>
  </div>
 <div class="field">
    <%= f.label :fosfataza_alcalina %>
    <%= f.text_field :fosfataza_alcalina %>
  </div>
 <div class="field">
    <%= f.label :albumina %>
    <%= f.text_field :albumina %>
  </div>
 <div class="field">
    <%= f.label :alfa1 %>
    <%= f.text_field :alfa1 %>
  </div>
 <div class="field">
    <%= f.label :alfa2 %>
    <%= f.text_field :alfa2 %>
  </div>
 <div class="field">
    <%= f.label :beta %>
    <%= f.text_field :beta %>
  </div>
 <div class="field">
    <%= f.label :gamma %>
    <%= f.text_field :gamma %>
  </div>

app/views/hemo_lunars/edit.html.erb
<h1>Editing hemo_lunar</h1>

<%= render 'form' %>

<%# link_to 'Show', @hemo_lunar %> 
<%# link_to 'Back', hemo_lunars_path %>

app/views/hemo_lunars/index.html.erb
<h1>Listing hemo_lunars</h1>

<table>
  <tr>
    <th>Data</th>
    <th>Pacient</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hemo_lunars.each do |hemo_lunar| %>
  <tr>
    <td><%= hemo_lunar.data %></td>
    <td><%= hemo_lunar.pacient.nume %></td>
    <td><%= link_to 'Show', pacient_hemo_lunar_path(@pacient, hemo_lunar) %></td>
    <td><%= link_to 'Edit', edit_pacient_hemo_lunar_path(@pacient, hemo_lunar) %></td>
    <td><%= link_to 'Destroy', pacient_hemo_lunar_path(@pacient, hemo_lunar), 
      :confirm => 'Are you sure?', 
      :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New hemo_lunar', new_hemo_lunar_path %>

app/views/hemo_lunars/new.html.erb
<h1>New hemo_lunar</h1>
<h2><%= @pacient.nume %></h2>
<%# render 'form' %>
<%= render :action => 'new_pacient_hemo_lunar', :partial => 'form' %>

<%= link_to 'Back', hemo_lunars_path %>

app/views/hemo_lunars/show.html.erb
<p id="notice"><%= notice %></p>
<h3> Aici urmeaza sa pun analize</h3>
<%= @hemo_lunar.data %>


<%# link_to 'Edit', edit_hemo_lunar_path(@hemo_lunar) %> |
<%# link_to 'Back', hemo_lunars_path %>