config/routes.rb
ProiectConf::Application.routes.draw do

  devise_for :users

  resources :pacients, :has_many => :diabets
  resources :pacients, :has_many => :protocols #, :member => { :last_protocol => :get }
  resources :pacients, :has_many => :capds
  resources :pacients, :hay_many => :hemo_lunars
  resources :pacients, :hay_many => :bcrs

  resources :pacients do 
    resources :capds
    resources :bcrs 
    resources :protocols 
    resources :diabets
    resources :hemo_lunars
    resources :hemo_semestrials
  end
  resources :diabets
  resources :hemo_lunars
  resources :bcrs
  resources :capds

  resources :protocols do 
    resources :centrus
  end

  resources :centrus 
  root :to => "pacients#index"

end

app/models/pacient.rb
class Pacient < ActiveRecord::Base
  has_many :protocols, :dependent => :destroy
  has_many :diabets
  has_many :hemo_lunars, :dependent => :destroy
  has_many :bcrs, :dependent => :destroy
  has_many :hemo_semestrials, :dependent => :destroy
  has_many :capds, :dependent => :destroy
  accepts_nested_attributes_for :protocols, :allow_destroy => true
  accepts_nested_attributes_for :hemo_lunars, :allow_destroy => true
  #validates_uniqueness_of :cnp, :message => "Ai deja un pacient cu acest CNP"
  def last_protocol
    unless self.protocols.last.nil?
      @protocols = self.protocols.last
    end
  end
end

app/controllers/pacients_controller.rb
class PacientsController < ApplicationController
  # GET /pacients
  # GET /pacients.xml
  before_filter :authenticate_user!
  def index
    @pacients = Pacient.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pacients }
    end
  end

  # GET /pacients/1
  # GET /pacients/1.xml
  def show
    @pacient = Pacient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pacient }
    end
  end

  # GET /pacients/new
  # GET /pacients/new.xml
  def new
    @pacient = Pacient.new
    @protocol = @pacient.protocols.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pacient }
    end
  end

  # GET /pacients/1/edit
  def edit
    @pacient = Pacient.find(params[:id])
  end

  # POST /pacients
  # POST /pacients.xml
  def create
    @pacient = Pacient.new(params[:pacient])
    if @pacient.save
      flash[:notice] = "bravo ai mai bagat un pacient"
      redirect_to @pacient
    else
      render :action => 'new'
    end

  end

  # PUT /pacients/1
  # PUT /pacients/1.xml
  def update
    @pacient = Pacient.find(params[:id])

    respond_to do |format|
      if @pacient.update_attributes(params[:pacient])
        format.html { redirect_to(@pacient, :notice => 'Pacient was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pacient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pacients/1
  # DELETE /pacients/1.xml
  def destroy
    @pacient = Pacient.find(params[:id])
    @pacient.destroy

    respond_to do |format|
      format.html { redirect_to(pacients_url) }
      format.xml  { head :ok }
    end
  end

  #def last_protocol
    #@protocol = Pacient.find(params[:id]).protocols.last
  #end



end

app/helpers/pacients_helper.rb
module PacientsHelper
  def link_to_analize(pacient)
    analiza_path = case pacient.last_protocol.program
      when 'capd' then analiza_path = new_pacient_capd_url(pacient)
      when 'hd' then analiza_path = new_pacient_hemo_lunar_url(pacient)
      when 'brd' then analiza_path = new_pacient_bcr_path(pacient)
      end

    link_to('Adauga alt set de analize', analiza_path)
  end
end

app/views/pacients/_form.html.erb
<%= simple_form_for @pacient do |f| %>

  <%= f.input :nume %>
  <%= f.input :prenume %>
  <%= f.input :cnp %><!-- de facut verificarea de 13 cifre -->
  <%= f.input :data_integrarii, :as => :date %>
  <%= f.simple_fields_for :protocols do |g| %>
    <%= g.input :data, :as => :date %>
    <%= g.input :centru, :as => :select, :collection => Protocol::CENTRE %>
    <%= g.input :program, :as => :select, :collection => Protocol::PROGRAME %>
  <% end %>
    
  <% f.fields_for :protocols do |builder| %>
    <%= render "protocols/form", :f => builder %>
  <% end %>
  <%= f.button :submit %>
<% end %>

app/views/pacients/_meniu_analize.html.erb
  <%= select(HemoLunar.column_names, {:prompt=>'selecteaza o analiza'})>

app/views/pacients/edit.html.erb
<h1>Editing pacient</h1>

<%= render 'form' %>
<h4> Aici merge un buton pentru update doar la protocol</h4>
<%= link_to 'Show', @pacient %> |
<%= link_to 'Back', pacients_path %>|
<%= link_to 'Schimba protocolul sau centrul', new_pacient_protocol_path(@pacient) %> <br/>
<%= link_to_analize %><br/>

app/views/pacients/index.html.erb
<h1>Listing pacients</h1>

<table>
  <tr>
    <th>Nume</th>
    <th>Prenume</th>
    <th>Cnp</th>
    <th> Tipul protocolului urmat</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pacients.each do |pacient| %>
  <tr>
    <td><%= pacient.nume %></td>
    <td><%= pacient.prenume %></td>
    <td><%= pacient.cnp %></td>
    <td align="center"><%= pacient.last_protocol.try(:program) %></td>
    <td><%= link_to 'Show', pacient %></td>
    <% if can? :update, pacient %>
      <td><%= link_to 'Edit', edit_pacient_path(pacient) %></td>
    <% end %>
    <% if can? :destroty, pacient %>
      <td><%= link_to 'Destroy', pacient, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pacient', new_pacient_path %>

app/views/pacients/new.html.erb
<h1>New pacient</h1>

<%= render 'form' %>

<%= link_to 'Back', pacients_path %>

app/views/pacients/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', pacients_path %>
<h2> Analizele lui <%= @pacient.nume %> <%= @pacient.prenume %> </h2>
<p>
  <b>Cnp:</b>
  <%= @pacient.cnp %>
</p>

<%= render :partial => "hemo_lunars/index" %><!-- asta nu e bine ca acu am mai multe modele de hemo -->
<%= link_to 'Editeaza datele pacientului sau ale protocolului', edit_pacient_path(@pacient) %> |
<%= link_to 'Schimba Protocolul', new_pacient_protocol_path(@pacient) %>|
<%= link_to_analize(@pacient) %>